version: '3.8'

services:
  web:
    build: .
    command: /bin/bash -c "python conec_db.py && python app.py"
    ports:
      - "5000:5000"
    env_file:
      - .env

  db:
    image: postgres
    ports:
    - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
